# necessary packages, functions/scripts, data
library(tidyverse)

source("00_scripts/SoIBv2_functions.R")


# PART 1 ------------------------------------------------------------------

# Run each step in order. May start from in between but progress sequentially down.

# Sequence of steps to clean data starting from .txt file:
# - clean the eBird EBD
# - remove unnecessary columns
# - add necessary columns
# Run:
# - after EVERY new EBD download
# Requires:
# - tidyverse, lubridate
# - EBD .txt file MUST BE in the working directory
# Outputs:
# - "indiaspecieslist.csv" (common and scientific names of all species)
# - "eBird_location_data.csv"
# - "rawdata.RData"

readcleanrawdata(rawpath = "00_data/ebd_IN_relFeb-2023.txt", 
                 sensitivepath = "00_data/ebd_sensitive_relFeb-2023_IN.txt")


# Create sf map of SoIB2 habitat masks
# Run:
# - every time habitat masks (input .json file) are updated
# Requires:
# - tidyverse, sf, geojsonsf
# - "soibV2GridsIN_habMasksAdded.geojson" (generated by line immediately below this block)
# Outputs:
# - "habmasks_sf.RData"

source("00_scripts/create_habitat_masks_dataframe.R")


# Add map and grid variables to dataset (dataframe)
# - admin & PA boundaries
# - SoIB2 habitat masks
# - square grids at 5 resolutions (5, 25, 50, 100, 200 km*km), unclipped and clipped to India
# Run:
# - after EVERY new EBD download
# - after loading "rawdata.RData" directly
# Requires:
# - tidyverse, sf
# - Data (ALL in 00_data/):
#   - "rawdata.RData"
#   - "grids_sf_full.RData", "grids_g0_sf.RData", "maps_sf.RData", "maps_pa_sf.RData"* 
#       See the India Maps repo:
#       https://github.com/birdcountindia/india-maps/blob/main/scripts/create_maps_sf.R
#   - "habmasks_sf.RData" (generated above)
# Outputs:
# - "data.RData"

addmapvars()


# Process and filter data for analyses
# Run:
# - after EVERY new EBD download
# - after loading "rawdata.RData" directly
# - after loading "data.RData" directly
# Requires:
# - tidyverse, lubridate
# - data files (ALL in 00_data/):
#   - "data.RData"
#   - "indiaspecieslist.csv" (common and scientific names of all species)
#   - "SoIB_mapping_2022.csv"
# Outputs:
# - "dataforanalyses_extra.RData"
# - "fullspecieslist.csv" and individual mask versions
# - "sub_samp_locs.csv" and individual mask versions
# - "dataforanalyses.RData" and individual mask versions, which contains:
#   - info on amount of data in each temporal bin
#   - full species list (with all attribute columns)
#   - selected species list
#   - data
# - specieslists.RData and individual mask versions

dataspeciesfilter(locationlimit = 15, gridlimit = 4, listlimit = 50)


## create random group IDs
## print data files
## run trend analyses




  ###################                       PART 2                     ###################################
## provide "dataforanalyses.RData", "neighbours.RData", "indiaspecieslist.csv" and 
## "Migratory Status - Migratory Status.csv"

## ALL SUBSEQUENT ANALYSES REQUIRE DATA THAT HAS BEEN THROUGH THE PREVIOUS STEPS
## if "dataforanalyses.RData" can be loaded and "indiaspecieslist.csv" is available, part 1 not required


## provides occupancy estimates for one or many species
## select one or more Indian bird species
## requires tidyverse, reshape2, data.table, unmarked
## "neighbours.RData", "indiaspecieslist", "Migratory Status - Migratory Status.csv" 
## MUST BE in the home folder
## returns a dataframe with occupancy values


source('00_scripts/SoIBv2_functions.R')
occ = SoIBoccupancy(data,species,areag=areag1)

## for the final run, species = specieslist$COMMON.NAME (or this incrementally)

source('00_scripts/SoIBv2_functions.R')
load("00_data/dataforanalyses.RData")
#load("finaloccupancy.RData")

#occ = SoIBoccupancy(data,species = specieslist$COMMON.NAME[1],areag = areag1)

occ = read.csv("occ.csv")
speciesleft = setdiff(specieslist$COMMON.NAME,occ$species)

#for (i in 2:length(specieslist$COMMON.NAME))
for (i in 1:length(speciesleft))
{
  #occ1 = SoIBoccupancy(data,species = specieslist$COMMON.NAME[i],areag = areag1)
  occ1 = SoIBoccupancy(data,species = speciesleft[i],areag = areag1)
  occ = rbind(occ,occ1)
  write.csv(occ,"occ.csv",row.names=FALSE)
}

for (i in 1:length(restrictedspecieslist$COMMON.NAME))
{
  species = restrictedspecieslist$COMMON.NAME[i]
  start = Sys.time()
  tre <- freqtrendsrestricted(data,species,specieslist = restrictedspecieslist,nsim = 1000)
  #tre <- freqtrends(data,species,specieslist = restrictedspecieslist)
  name = paste(species,".RData",sep="")
  save(tre,file = name)
  end = Sys.time()
  print(end-start)
}





