# necessary packages, functions/scripts, data
library(tidyverse)
library(glue)
library(tictoc)

source("00_scripts/00_functions.R")


# PART 1 ------------------------------------------------------------------

# Run each step in order. May start from in between but progress sequentially down.

# STEP 1: Sequence of steps to clean data starting from .txt file:
# - clean the eBird EBD
# - remove unnecessary columns
# - add necessary columns
# Run:
# - after EVERY new EBD download
# Requires:
# - tidyverse, lubridate
# - EBD .txt file MUST BE in the working directory
# Outputs:
# - "indiaspecieslist.csv" (common and scientific names of all species)
# - "eBird_location_data.csv"
# - "rawdata.RData"

readcleanrawdata(rawpath = "00_data/ebd_IN_relFeb-2023.txt", 
                 sensitivepath = "00_data/ebd_sensitive_relFeb-2023_IN.txt")


# STEP 2: Create sf map of SoIB2 habitat masks
# Run:
# - every time habitat masks (input .json file) are updated
# Requires:
# - tidyverse, sf, geojsonsf
# - "soibV2GridsIN_habMasksAdded.geojson" (generated by line immediately below this block)
# Outputs:
# - "habmasks_sf.RData"

source("00_scripts/create_habitat_masks_dataframe.R")


# STEP 3: Add map and grid variables to dataset (dataframe)
# - admin & PA boundaries
# - SoIB2 habitat masks
# - square grids at 5 resolutions (5, 25, 50, 100, 200 km*km), unclipped and clipped to India
# Run:
# - every time habitat masks or other maps are updated
# - every time "rawdata.RData" is updated
# Requires:
# - tidyverse, sf
# - Data (ALL in 00_data/):
#   - "rawdata.RData"
#   - "grids_sf_full.RData", "grids_g0_sf.RData", "maps_sf.RData", "maps_pa_sf.RData"* 
#       See the India Maps repo:
#       https://github.com/birdcountindia/india-maps/blob/main/scripts/create_maps_sf.R
#   - "habmasks_sf.RData" (generated above)
# Outputs:
# - "data.RData"

addmapvars()


# STEP 4: create and save metadata for processing analyses for various masks
# Run:
# - every time analysis skeleton/various masks are updated
# Requires:
# - tidyverse, glue
# Outputs:
# - "analyses_metadata.RData"
analyses_metadata <- data.frame(MASK = c("none", 
                                         "woodland", "cropland", "ONEland", 
                                         "PA",
                                         "Kerala")) %>% 
  mutate(FOLDER = case_when(MASK == "none" ~ "01_analyses_full/", 
                            MASK %in% c("woodland", "cropland", "ONEland", "PA") ~ glue("01_analyses_mask-{MASK}/"),
                            TRUE ~ glue("01_analyses_states/{MASK}/"))) %>% 
  mutate(FULLSPECLIST.PATH = glue("{FOLDER}fullspecieslist.csv"),
         LOCS.PATH = glue("{FOLDER}sub_samp_locs.csv"),
         SPECLISTDATA.PATH = glue("{FOLDER}specieslists.RData"),
         DATA.PATH = glue("{FOLDER}dataforanalyses.RData"),
         RAND.GROUP.IDS.PATH = glue("{FOLDER}randomgroupids.RData"),
         SIMDATA.PATHONLY = glue("{FOLDER}dataforsim/"),
         TRENDS.PATHONLY = glue("{FOLDER}trends/"),
         SOIBMAIN.PATH = glue("{FOLDER}SoIB_main.csv"),
         TRENDS.OUTPATH = glue("{FOLDER}trends.csv"))

# ensuring folders are created if they don't already exist
for (i in 1:length(analyses_metadata$FOLDER)) {
  
  if (!dir.exists(analyses_metadata$FOLDER[i])) {
    dir.create(analyses_metadata$FOLDER[i], 
               recursive = T)
  }
  
}

# for later reference
save(analyses_metadata, 
     file = "00_data/analyses_metadata.RData")



# STEP 5: Process and filter data for analyses
# Run:
# - every time "data.RData" is updated
# Requires:
# - tidyverse, lubridate
# - data files (ALL in 00_data/):
#   - "data.RData"
#   - "indiaspecieslist.csv" (common and scientific names of all species)
#   - "SoIB_mapping_2022.csv"
# Outputs:
# - "analyses_metadata.RData"
# - "dataforanalyses_extra.RData"
# - "fullspecieslist.csv" for whole country and individual mask versions
# - "sub_samp_locs.csv" for whole country and individual mask versions
# - "dataforanalyses.RData" for whole country and individual mask versions, which contains:
#   - info on amount of data in each temporal bin
#   - full species list (with all attribute columns)
#   - selected species list
#   - data
# - specieslists.RData for whole country and individual mask versions

load("00_data/analyses_metadata.RData")

source("00_scripts/filter_data_for_species.R")


# PART 2 ------------------------------------------------------------------

# Preparing data for trends analysis


# STEP 1: Subsample data for locations (create set of randomly selected GROUP.IDs)
# <annotation_pending_AV> why do we do this in the first place?
# Run:
# - every time "sub_samp_locs.csv" is updated
# Requires:
# - tidyverse, parallel, foreach, doParallel, tictoc
# - data files (ALL in 00_data/):
#   - "sub_samp_locs.csv" for whole country and individual mask versions
# Outputs:
# - "randomgroupids.RData" for whole country and individual mask versions

load("00_data/analyses_metadata.RData")

# not functionising because parallelisation doesn't work inside functions
cur_mask <- "none"
tictoc::tic("generated random group IDs for full country")
source("00_scripts/create_random_groupids.R")
tictoc::toc() # 83 min

cur_mask <- "woodland"
tictoc::tic("generated random group IDs for woodland")
source("00_scripts/create_random_groupids.R")
tictoc::toc() # 2331 sec (38 min)

cur_mask <- "cropland"
tictoc::tic("generated random group IDs for cropland")
source("00_scripts/create_random_groupids.R")
tictoc::toc() # 833 sec (14 min)

cur_mask <- "ONEland"
tictoc::tic("generated random group IDs for ONEland")
source("00_scripts/create_random_groupids.R")
tictoc::toc() # 463 sec (8 min)

cur_mask <- "PA"
tictoc::tic("generated random group IDs for PA")
source("00_scripts/create_random_groupids.R")
tictoc::toc() # 409 sec (7 min)

cur_mask <- "Kerala"
tictoc::tic("generated random group IDs for Kerala")
source("00_scripts/create_random_groupids.R")
tictoc::toc() # 



# STEP 2: Create subsampled data files using subsampled GROUP.IDs
# Run:
# - after above step (P2, S1)
# Requires:
# - tidyverse, tictoc
# - data files (ALL in 00_data/):
#   - "dataforanalyses.RData" for whole country and individual mask versions
#   - "randomgroupids.RData" for whole country and individual mask versions
# Outputs:
# - "dataforsim/dataX.csv" for whole country and individual mask versions

load("00_data/analyses_metadata.RData")


# FULL COUNTRY

cur_mask <- "none"
my_assignment <- 201:400 # CHANGE FOR YOUR SUBSET
tictoc::tic(glue("Generated subsampled data for full country (# {min(my_assignment)}:{max(my_assignment)})"))
source("00_scripts/create_random_datafiles.R")
tictoc::toc() 


# INDIVIDUAL MASKS

cur_mask <- "woodland"
tictoc::tic("Generated subsampled data for woodland")
source("00_scripts/create_random_datafiles.R")
tictoc::toc() 

cur_mask <- "cropland"
tictoc::tic("Generated subsampled data for cropland")
source("00_scripts/create_random_datafiles.R")
tictoc::toc() 

cur_mask <- "ONEland"
tictoc::tic("Generated subsampled data for ONEland")
source("00_scripts/create_random_datafiles.R")
tictoc::toc() 

cur_mask <- "PA"
tictoc::tic("Generated subsampled data for PA")
source("00_scripts/create_random_datafiles.R")
tictoc::toc() 

cur_mask <- "Kerala"
tictoc::tic("Generated subsampled data for Kerala")
source("00_scripts/create_random_datafiles.R")
tictoc::toc() # 



# PART 3 ------------------------------------------------------------------

# STEP 1: Run trends models for all selected species
# Run:
# - after above step (P2, S2)
# Requires:
# - tidyverse, tictoc, lme4, VGAM, parallel, foreach, doParallel
# - data files (ALL in 00_data/):
#   - "dataforanalyses.RData" for whole country and individual mask versions
#   - "specieslists.RData" for whole country and individual mask versions
# Outputs:
# - "trends/trendsX.csv" for whole country and individual mask versions

load("00_data/analyses_metadata.RData")

# not functionising because parallelisation doesn't work inside functions
cur_mask <- "none"
my_assignment <- 122:200 # CHANGE FOR YOUR SUBSET
tictoc::tic(glue("Species trends for full country (sims {min(my_assignment)}--{max(my_assignment)})"))
source("00_scripts/run_species_trends.R")
tictoc::toc() 

cur_mask <- "woodland"
my_assignment <- 101:200 # CHANGE FOR YOUR SUBSET
tictoc::tic(glue("Species trends for woodland (sims {min(my_assignment)}--{max(my_assignment)})"))
source("00_scripts/run_species_trends.R")
tictoc::toc() 

cur_mask <- "cropland"
my_assignment <- 101:200 # CHANGE FOR YOUR SUBSET
tictoc::tic(glue("Species trends for cropland (sims {min(my_assignment)}--{max(my_assignment)})"))
source("00_scripts/run_species_trends.R")
tictoc::toc() 

cur_mask <- "ONEland"
my_assignment <- 101:200 # CHANGE FOR YOUR SUBSET
tictoc::tic(glue("Species trends for ONEland (sims {min(my_assignment)}--{max(my_assignment)})"))
source("00_scripts/run_species_trends.R")
tictoc::toc() 

cur_mask <- "PA"
my_assignment <- 49:200 # CHANGE FOR YOUR SUBSET
tictoc::tic(glue("Species trends for PA (sims {min(my_assignment)}--{max(my_assignment)})"))
source("00_scripts/run_species_trends.R")
tictoc::toc() # 195 sec for 1 sim (~ 11 hours for 200 sim)

cur_mask <- "Kerala"
my_assignment <- 1:200 # CHANGE FOR YOUR SUBSET
tictoc::tic(glue("Species trends for Kerala (sims {min(my_assignment)}--{max(my_assignment)})"))
source("00_scripts/run_species_trends.R")
tictoc::toc() # 



  ###################                       PART 3                     ###################################
## provide "dataforanalyses.RData", "neighbours.RData", "indiaspecieslist.csv" and 
## "Migratory Status - Migratory Status.csv"

## ALL SUBSEQUENT ANALYSES REQUIRE DATA THAT HAS BEEN THROUGH THE PREVIOUS STEPS
## if "dataforanalyses.RData" can be loaded and "indiaspecieslist.csv" is available, part 1 not required


## provides occupancy estimates for one or many species
## select one or more Indian bird species
## requires tidyverse, reshape2, data.table, unmarked
## "neighbours.RData", "indiaspecieslist", "Migratory Status - Migratory Status.csv" 
## MUST BE in the home folder
## returns a dataframe with occupancy values


source('00_scripts/SoIBv2_functions.R')
occ = SoIBoccupancy(data,species,areag=areag1)

## for the final run, species = specieslist$COMMON.NAME (or this incrementally)

source('00_scripts/SoIBv2_functions.R')
load("00_data/dataforanalyses.RData")
#load("finaloccupancy.RData")

#occ = SoIBoccupancy(data,species = specieslist$COMMON.NAME[1],areag = areag1)

occ = read.csv("occ.csv")
speciesleft = setdiff(specieslist$COMMON.NAME,occ$species)

#for (i in 2:length(specieslist$COMMON.NAME))
for (i in 1:length(speciesleft))
{
  #occ1 = SoIBoccupancy(data,species = specieslist$COMMON.NAME[i],areag = areag1)
  occ1 = SoIBoccupancy(data,species = speciesleft[i],areag = areag1)
  occ = rbind(occ,occ1)
  write.csv(occ,"occ.csv",row.names=FALSE)
}

for (i in 1:length(restrictedspecieslist$COMMON.NAME))
{
  species = restrictedspecieslist$COMMON.NAME[i]
  start = Sys.time()
  tre <- freqtrendsrestricted(data,species,specieslist = restrictedspecieslist,nsim = 1000)
  #tre <- freqtrends(data,species,specieslist = restrictedspecieslist)
  name = paste(species,".RData",sep="")
  save(tre,file = name)
  end = Sys.time()
  print(end-start)
}





